[package]
name = "egotoons"
version = "0.1.0"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aes-gcm = { version = "0.10", default-features = false, features = ["aes", "alloc"] }
base64 = "0.22"
manatan-extension = { git = "https://github.com/KolbyML/manatan-rs", default-features = false }
manatan-shared = { path = "../../../shared/manatan-shared" }
pbkdf2 = "0.12"
serde_json = "1"
sha2 = "0.10"
