[package]
name = "keenspot"
version = "0.1.0"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
manatan-extension = { git = "https://github.com/KolbyML/manatan-rs", default-features = false }
manatan-shared = { path = "../../../shared/manatan-shared" }
serde_json = "1"
