[package]
name = "manatan-novel-en-shanghaifantasy"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
manatan-sdk.workspace = true
manatan-common.workspace = true
wordpress-novel = { path = "../../../shared/wordpress-novel" }
serde_json.workspace = true
url.workspace = true
