[package]
name = "manatan-shared"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
manatan-extension.workspace = true
aes = "0.8"
base64 = "0.22"
cbc = { version = "0.1", features = ["alloc", "block-padding"] }
ctr = "0.9"
hmac = "0.12"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
rand_chacha = { version = "0.3", default-features = false }
rand_core = { version = "0.6", default-features = false }
rsa = { version = "0.9", default-features = false, features = ["sha2", "u64_digit"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
