[package]
name = "pawmanga"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
madara-manga.workspace = true
manatan-sdk.workspace = true

[dev-dependencies]
serde_json.workspace = true
sha2.workspace = true
