[package]
name = "manatan-novel-ja-hameln"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono.workspace = true
manatan-common.workspace = true
manatan-sdk.workspace = true
serde_json.workspace = true
url.workspace = true
