[package]
name = "rawkuma"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
manatan-sdk.workspace = true
natsuid-manga = { path = "../../../shared/natsuid-manga" }

[dev-dependencies]
serde_json.workspace = true
sha2.workspace = true
